name = "blackroad-metaverse"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[[routes]]
pattern = "blackroad.io/*"
zone_name = "blackroad.io"

[[routes]]
pattern = "www.blackroad.io/*"
zone_name = "blackroad.io"
