name = "blackroad-tools"
main = "worker.js"
compatibility_date = "2024-12-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"

[[custom_domains]]
pattern = "blackroad.io"
[[custom_domains]]
pattern = "www.blackroad.io"
[[custom_domains]]
pattern = "blackroad.me"
[[custom_domains]]
pattern = "blackroad.network"
[[custom_domains]]
pattern = "blackroad.systems"
[[custom_domains]]
pattern = "blackroad.company"
[[custom_domains]]
pattern = "blackroadai.com"
[[custom_domains]]
pattern = "blackroadinc.us"
[[custom_domains]]
pattern = "blackroadqi.com"
[[custom_domains]]
pattern = "blackroadquantum.com"
[[custom_domains]]
pattern = "blackroadquantum.net"
[[custom_domains]]
pattern = "blackroadquantum.info"
[[custom_domains]]
pattern = "blackroadquantum.shop"
[[custom_domains]]
pattern = "blackroadquantum.store"
[[custom_domains]]
pattern = "lucidia.earth"
[[custom_domains]]
pattern = "lucidia.studio"
[[custom_domains]]
pattern = "lucidiaqi.com"
[[custom_domains]]
pattern = "aliceqi.com"
[[custom_domains]]
pattern = "roadchain.io"
[[custom_domains]]
pattern = "roadcoin.io"
[[custom_domains]]
pattern = "blackboxprogramming.io"
