name = "blackroad-drive"
main = "worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "848cf0b18d51e0170e0d1537aec3505a"

[[custom_domains]]
hostname = "drive.blackroad.io"
