name = "blackroad-alice"
main = "index.js"
compatibility_date = "2025-01-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"

[vars]
AGENT_NAME = "ALICE"
BLACKROAD_GATEWAY_URL = "https://api.blackroad.io"
BLACKROAD_PI_PRIMARY = "http://192.168.4.38:4010"
BLACKROAD_PI_ALICE = "http://192.168.4.49:8001"
BLACKROAD_MODEL_SERVER = "https://api.blackroad.io"
BLACKROAD_QDRANT = "http://192.168.4.49:6333"
