name = "lucidia-earth"
account_id = "848cf0b18d51e0170e0d1537aec3505a"
compatibility_date = "2024-12-01"

[env.production]
routes = [
  { pattern = "lucidia.earth", custom_domain = true },
  { pattern = "www.lucidia.earth", custom_domain = true }
]
